#!/usr/bin/env python3
"""Validate the repository's agent skills and keep the Claude Code mirror in sync.

Canonical skills live in .agents/skills/ and are read directly by Codex.
Claude Code only reads .claude/skills/, so that tree is generated from the
canonical one.

    python3 scripts/validate-agent-skills.py           validate, change nothing
    python3 scripts/validate-agent-skills.py --sync    regenerate the mirror

The script only ever writes below .claude/skills/. It uses the standard library
only and runs the same way on Windows, macOS and Linux.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CANONICAL_DIR = REPO_ROOT / ".agents" / "skills"
MIRROR_DIR = REPO_ROOT / ".claude" / "skills"

CANONICAL_REL = ".agents/skills"
MIRROR_REL = ".claude/skills"

SKILL_FILE = "SKILL.md"
NAME_PATTERN = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
MAX_NAME_LENGTH = 64

# The six fields of the Agent Skills specification. Codex requires name and
# description; Claude Code requires description and rejects unknown keys when a
# skill is validated outside the CLI.
ALLOWED_FRONTMATTER_KEYS = {
    "name",
    "description",
    "license",
    "compatibility",
    "metadata",
    "allowed-tools",
}
REQUIRED_FRONTMATTER_KEYS = ("name", "description")

DISALLOWED_FILE_PATTERN = re.compile(r"^(readme|changelog|install|contributing)\b", re.IGNORECASE)
OPTIONAL_SUBDIRECTORIES = ("references", "scripts", "assets")

PLACEHOLDER_PATTERN = re.compile(r"\b(TODO|FIXME|TBD|XXX|PLACEHOLDER)\b|<your-|lorem ipsum", re.IGNORECASE)
ABSOLUTE_PATH_PATTERNS = (
    re.compile(r"(?<![A-Za-z])[A-Za-z]:\\"),
    re.compile(r"/home/[A-Za-z0-9._-]+"),
    re.compile(r"/Users/[A-Za-z0-9._-]+"),
    re.compile(r"/root/"),
    re.compile(r"file://"),
)
REFERENCE_PATTERN = re.compile(r"references/[A-Za-z0-9._/-]+\.[A-Za-z0-9]+")

BANNER_TEMPLATE = (
    "<!-- Generated from {source}. Do not edit this file directly. "
    "Edit the canonical copy and run: python3 scripts/validate-agent-skills.py --sync -->"
)


def read_text(path: Path) -> str:
    """Read a file and normalize line endings so a CRLF checkout does not look stale."""
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def split_frontmatter(content: str) -> tuple[list[str] | None, str]:
    """Return the frontmatter lines and the body, or (None, content) when absent."""
    if not content.startswith("---\n"):
        return None, content

    end = content.find("\n---\n", 3)
    if end == -1:
        return None, content

    frontmatter = content[4:end].split("\n")
    body = content[end + len("\n---\n") :]
    return frontmatter, body


def parse_frontmatter(lines: list[str]) -> tuple[dict[str, str], list[str]]:
    """Parse simple `key: value` scalars. Reject anything more complex."""
    parsed: dict[str, str] = {}
    problems: list[str] = []

    for raw in lines:
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        if raw[:1] in (" ", "\t", "-"):
            problems.append(
                f"frontmatter line is not a simple `key: value` scalar: {raw.strip()!r}"
            )
            continue
        if ":" not in raw:
            problems.append(f"frontmatter line has no colon: {raw.strip()!r}")
            continue

        key, _, value = raw.partition(":")
        key = key.strip()
        value = value.strip()
        if key in parsed:
            problems.append(f"duplicate frontmatter key: {key}")
        if not value:
            problems.append(f"frontmatter key `{key}` has an empty or multi-line value")
        parsed[key] = value

    return parsed, problems


def iter_skill_directories(root: Path) -> list[Path]:
    if not root.is_dir():
        return []
    return sorted(child for child in root.iterdir() if child.is_dir())


def iter_skill_files(skill_dir: Path) -> list[Path]:
    """Every file belonging to a skill, relative to the skill directory."""
    return sorted(
        path.relative_to(skill_dir)
        for path in skill_dir.rglob("*")
        if path.is_file()
    )


def rel_posix(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def build_mirror_content(source_rel: str, content: str) -> str:
    """Insert the do-not-edit banner, after the frontmatter when there is one."""
    banner = BANNER_TEMPLATE.format(source=source_rel)
    frontmatter, body = split_frontmatter(content)

    if frontmatter is None:
        return f"{banner}\n\n{content.lstrip(chr(10))}"

    joined = "\n".join(frontmatter)
    return f"---\n{joined}\n---\n\n{banner}\n{body.lstrip(chr(10))}"


def validate_skill(skill_dir: Path) -> list[str]:
    problems: list[str] = []
    directory_name = skill_dir.name
    skill_md = skill_dir / SKILL_FILE

    if not skill_md.is_file():
        return [f"{rel_posix(skill_dir)}: missing {SKILL_FILE}"]

    content = read_text(skill_md)
    frontmatter, body = split_frontmatter(content)

    if frontmatter is None:
        problems.append(
            f"{rel_posix(skill_md)}: missing or unterminated YAML frontmatter "
            "(the file must start with `---` and close with `---`)"
        )
        return problems

    parsed, frontmatter_problems = parse_frontmatter(frontmatter)
    problems.extend(f"{rel_posix(skill_md)}: {item}" for item in frontmatter_problems)

    for key in REQUIRED_FRONTMATTER_KEYS:
        if key not in parsed:
            problems.append(f"{rel_posix(skill_md)}: frontmatter is missing required key `{key}`")

    unknown = sorted(set(parsed) - ALLOWED_FRONTMATTER_KEYS)
    if unknown:
        problems.append(
            f"{rel_posix(skill_md)}: frontmatter has keys outside the Agent Skills "
            f"specification: {', '.join(unknown)}"
        )

    name = parsed.get("name", "")
    if name:
        if name != directory_name:
            problems.append(
                f"{rel_posix(skill_md)}: frontmatter name `{name}` does not match "
                f"directory name `{directory_name}`"
            )
        if not NAME_PATTERN.match(name):
            problems.append(
                f"{rel_posix(skill_md)}: name `{name}` must be lowercase kebab-case"
            )
        if len(name) >= MAX_NAME_LENGTH:
            problems.append(
                f"{rel_posix(skill_md)}: name is {len(name)} characters, "
                f"must be shorter than {MAX_NAME_LENGTH}"
            )

    description = parsed.get("description", "")
    if description and len(description) < 40:
        problems.append(
            f"{rel_posix(skill_md)}: description is too short to drive automatic "
            "triggering; state both the purpose and when to use the skill"
        )

    if not body.strip():
        problems.append(f"{rel_posix(skill_md)}: body is empty")

    # Files that must not live inside a skill directory.
    for relative in iter_skill_files(skill_dir):
        if DISALLOWED_FILE_PATTERN.match(relative.name):
            problems.append(
                f"{rel_posix(skill_dir / relative)}: a skill directory must not contain "
                "a readme, changelog, install or contributing file"
            )

    # Optional subdirectories must not be empty.
    for name_ in OPTIONAL_SUBDIRECTORIES:
        candidate = skill_dir / name_
        if candidate.is_dir() and not any(candidate.rglob("*")):
            problems.append(f"{rel_posix(candidate)}: empty `{name_}` directory, remove it")

    # Referenced repository-local reference files must exist.
    for match in sorted(set(REFERENCE_PATTERN.findall(content))):
        if not (skill_dir / match).is_file():
            problems.append(
                f"{rel_posix(skill_md)}: references `{match}`, which does not exist"
            )

    # Content hygiene across every file of the skill.
    for relative in iter_skill_files(skill_dir):
        path = skill_dir / relative
        if path.suffix.lower() not in (".md", ".txt"):
            continue
        text = read_text(path)
        placeholder = PLACEHOLDER_PATTERN.search(text)
        if placeholder:
            problems.append(
                f"{rel_posix(path)}: contains placeholder text {placeholder.group(0)!r}"
            )
        for pattern in ABSOLUTE_PATH_PATTERNS:
            found = pattern.search(text)
            if found:
                problems.append(
                    f"{rel_posix(path)}: contains an absolute local path {found.group(0)!r}"
                )
                break

    return problems


def check_mirror(sync: bool) -> list[str]:
    problems: list[str] = []
    canonical_skills = iter_skill_directories(CANONICAL_DIR)
    expected: dict[Path, str] = {}

    for skill_dir in canonical_skills:
        for relative in iter_skill_files(skill_dir):
            source = skill_dir / relative
            target = MIRROR_DIR / skill_dir.name / relative
            if source.suffix.lower() == ".md":
                expected[target] = build_mirror_content(rel_posix(source), read_text(source))
            else:
                expected[target] = read_text(source)

    if sync:
        MIRROR_DIR.mkdir(parents=True, exist_ok=True)
        for target, content in expected.items():
            write_text(target, content)

        # Remove files the canonical tree no longer produces.
        for path in sorted(MIRROR_DIR.rglob("*"), reverse=True):
            if path.is_file() and path not in expected:
                path.unlink()
            elif path.is_dir() and not any(path.iterdir()):
                path.rmdir()
        return problems

    for target, content in sorted(expected.items()):
        if not target.is_file():
            problems.append(f"{rel_posix(target)}: missing from the {MIRROR_REL} mirror")
        elif read_text(target) != content:
            problems.append(f"{rel_posix(target)}: out of date with respect to {CANONICAL_REL}")

    if MIRROR_DIR.is_dir():
        for path in sorted(MIRROR_DIR.rglob("*")):
            if path.is_file() and path not in expected:
                problems.append(
                    f"{rel_posix(path)}: present in the mirror but not in {CANONICAL_REL}"
                )

    return problems


def check_instruction_files() -> list[str]:
    problems: list[str] = []
    agents_md = REPO_ROOT / "AGENTS.md"
    claude_md = REPO_ROOT / "CLAUDE.md"

    if not agents_md.is_file():
        problems.append("AGENTS.md: missing")
    if not claude_md.is_file():
        problems.append("CLAUDE.md: missing")
        return problems

    claude_lines = read_text(claude_md).split("\n")
    if not any(line.strip() == "@AGENTS.md" for line in claude_lines):
        problems.append(
            "CLAUDE.md: must import the shared rules with a line containing exactly "
            "`@AGENTS.md`, otherwise the two agents can diverge"
        )

    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--sync",
        action="store_true",
        help=f"regenerate {MIRROR_REL} from {CANONICAL_REL} instead of only checking it",
    )
    args = parser.parse_args()

    if not CANONICAL_DIR.is_dir():
        print(f"FAIL: canonical skills directory {CANONICAL_REL} does not exist")
        return 1

    skills = iter_skill_directories(CANONICAL_DIR)
    if not skills:
        print(f"FAIL: no skills found under {CANONICAL_REL}")
        return 1

    problems: list[str] = []
    for skill_dir in skills:
        problems.extend(validate_skill(skill_dir))

    problems.extend(check_instruction_files())
    problems.extend(check_mirror(sync=args.sync))

    if problems:
        print(f"FAIL: {len(problems)} problem(s) found\n")
        for problem in problems:
            print(f"  - {problem}")
        if not args.sync:
            print(
                "\nIf the mirror is stale, run: "
                "python3 scripts/validate-agent-skills.py --sync"
            )
        return 1

    action = "validated and synced" if args.sync else "validated"
    print(f"PASS: {len(skills)} skill(s) {action}")
    for skill_dir in skills:
        print(f"  - {skill_dir.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
